# NumPy 

In [2]:
import numpy as np

## Creating 1D array.

In [3]:
arr1 = np.array([2,3,4])
print(arr1)

# Array Indexing
print(arr1[:2])
print(arr1[0])

# Matrix operations
arr2 = np.array([5,2,4])
b = 3

print(arr1+arr2)
print(b+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

# Matrix Operations using numpy functions.
print(np.add(arr1,arr2))
print(np.add(arr1,b))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[2 3 4]
[2 3]
2
[7 5 8]
[8 5 7]
[-3  1  0]
[10  6 16]
[0.4 1.5 1. ]
[7 5 8]
[5 6 7]
[-3  1  0]
[10  6 16]
[0.4 1.5 1. ]


## Creating 2D array.

In [4]:
arr1 = np.array([(2,4,6),(3,8,7)])
print(arr1)
arr2 = np.array([(123,456,789),(987,654,321)])

print("\n")
# 2D array indexing
print(arr1[0,1])
print(arr2[:,2])
print(arr2[0,1:2])

arr3 = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])
print("\n")
print(arr3[:2,1:])

# Matrix Operation.
print("\n")
print(np.add(arr1,arr2),"\n")
print(np.add(arr1,arr2),"\n")
print(np.add(arr1,b),"\n")
print(np.subtract(arr1,arr2),"\n")
print(np.multiply(arr1,arr2),"\n")
print(np.divide(arr1,arr2),"\n")

[[2 4 6]
 [3 8 7]]


4
[789 321]
[456]


[[8 7]
 [5 4]]


[[125 460 795]
 [990 662 328]] 

[[125 460 795]
 [990 662 328]] 

[[ 5  7  9]
 [ 6 11 10]] 

[[-121 -452 -783]
 [-984 -646 -314]] 

[[ 246 1824 4734]
 [2961 5232 2247]] 

[[0.01626016 0.00877193 0.00760456]
 [0.00303951 0.01223242 0.02180685]] 



# Using Functions

In [5]:
new_arr = np.array([21293847198723984791723,3123452345636745856,423452345235611232431234154,512341234523456236,612345712873541897235987891723985798718975479])

new_arr1 = np.array([1,2,3,4,67])

print(new_arr)

# itemsize() function
print(new_arr.itemsize)

print("\n",new_arr1)
print(new_arr1.itemsize)

# dtype() function
print(new_arr.dtype)
print(new_arr[1])

print(new_arr1.dtype)

[21293847198723984791723 3123452345636745856 423452345235611232431234154
 512341234523456236 612345712873541897235987891723985798718975479]
8

 [ 1  2  3  4 67]
4
object
3123452345636745856
int32


## Knowing the Dimensions of arrays (Using ndim() function)

ndim() function returns the number dimensions of array.

In [6]:
new_arr2 = np.array([[1,2,3,4],
                     [3,5,6,7],
                     [4,5,67,8],
                     [5,6,2,4]])

new_arr3 = np.array([[(4,5,67,8),(5,6,2,4)],[(123,23,42,35),(123,4,6,23)]])


print(new_arr2.ndim)
print(new_arr3.ndim)

# 3D array Indexing
print(new_arr3[1,0,1])

2
3
23


## Know the Size of array

In [7]:
print(new_arr3.size)
#print(new_arr2.size)

16


## Know the Shape of array

In [8]:
print(new_arr3.shape)
print(new_arr2.shape)

(2, 2, 4)
(4, 4)


## Using arange() and reshape() Function

In [9]:
sample = np.arange(10)
print(sample)
print("\nShape :: ",sample.shape)

sample1 = np.arange(10).reshape(2,5)
print("\n",sample1)
print("\nNew shape :: ",sample1.shape)

# Creating and reshaping in 3D array
arr = np.arange(12).reshape((2,2,3))
print("\n",arr)

[0 1 2 3 4 5 6 7 8 9]

Shape ::  (10,)

 [[0 1 2 3 4]
 [5 6 7 8 9]]

New shape ::  (2, 5)

 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


## Using linspace() function for array creation

In [10]:
arr_w_linspc = np.linspace(1,50,4)
print(arr_w_linspc)

arr_w_linspc = np.linspace(1,50,200)
print("\n",arr_w_linspc)

[ 1.         17.33333333 33.66666667 50.        ]

 [ 1.          1.24623116  1.49246231  1.73869347  1.98492462  2.23115578
  2.47738693  2.72361809  2.96984925  3.2160804   3.46231156  3.70854271
  3.95477387  4.20100503  4.44723618  4.69346734  4.93969849  5.18592965
  5.4321608   5.67839196  5.92462312  6.17085427  6.41708543  6.66331658
  6.90954774  7.15577889  7.40201005  7.64824121  7.89447236  8.14070352
  8.38693467  8.63316583  8.87939698  9.12562814  9.3718593   9.61809045
  9.86432161 10.11055276 10.35678392 10.60301508 10.84924623 11.09547739
 11.34170854 11.5879397  11.83417085 12.08040201 12.32663317 12.57286432
 12.81909548 13.06532663 13.31155779 13.55778894 13.8040201  14.05025126
 14.29648241 14.54271357 14.78894472 15.03517588 15.28140704 15.52763819
 15.77386935 16.0201005  16.26633166 16.51256281 16.75879397 17.00502513
 17.25125628 17.49748744 17.74371859 17.98994975 18.2361809  18.48241206
 18.72864322 18.97487437 19.22110553 19.46733668 19.71356784 19.95979899

## Using max(), min() and sum() function

In [11]:
arr = np.array([[1,2,3,4],
                [3,5,6,7],
                [4,5,67,8],
                [5,6,2,4]])
arrc = np.arange(15)
print(arr)
print(arr.max())
print(arr.min())
print(arr.sum())

print("\n",arrc)
print(arrc.max())
print(arrc.min())
print(arrc.sum())

[[ 1  2  3  4]
 [ 3  5  6  7]
 [ 4  5 67  8]
 [ 5  6  2  4]]
67
1
132

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14
0
105


## Using sqrt function

In [12]:
print(np.sqrt(arrc))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


## Calculating standard deviation 

In [13]:
print(np.std(arr))
print(np.std(arrc))

15.278661590597522
4.320493798938574


## Using exponantial function

In [14]:
print(np.exp(arrc))
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [2.00855369e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [5.45981500e+01 1.48413159e+02 1.25236317e+29 2.98095799e+03]
 [1.48413159e+02 4.03428793e+02 7.38905610e+00 5.45981500e+01]]


## Using log function

In [15]:
print(np.log(arr))

[[0.         0.69314718 1.09861229 1.38629436]
 [1.09861229 1.60943791 1.79175947 1.94591015]
 [1.38629436 1.60943791 4.20469262 2.07944154]
 [1.60943791 1.79175947 0.69314718 1.38629436]]


## Using ravel function

In [16]:
arrr = np.array([(32,5,2),(1,54,16)])
print(arrr)
print(arrr.ravel())  ##this function converts any array into flatened/1-d array

[[32  5  2]
 [ 1 54 16]]
[32  5  2  1 54 16]


## Creating array with one constant valuel.

In [18]:
const = np.full((2,3),4)
print(const)

[[4 4 4]
 [4 4 4]]


## Creating array with only 1 value

In [20]:
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Creating Zero matrix

In [22]:
zero = np.zeros((3,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Boolean Array Indexing

In [32]:
arr = np.arange(10).reshape(5,2)
print(arr)

print("\n",arr>2)

print("\n",arr[arr>2])

print("\n",arr != 5)

print("\n",arr[arr !=5])

print("\n",arr[arr ==5])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 [[False False]
 [False  True]
 [ True  True]
 [ True  True]
 [ True  True]]

 [3 4 5 6 7 8 9]

 [[ True  True]
 [ True  True]
 [ True False]
 [ True  True]
 [ True  True]]

 [0 1 2 3 4 6 7 8 9]

 [5]
