# Introduction to SciPy library.

In [2]:
import scipy as sp
from scipy import special

In [3]:
# using kelvin funcion
func = special.kelvin(18)
print(func)

((30962.327279773937-7454.337021846366j), (7.438083958045599e-07-4.555469696791113e-07j), (26298.423535632264+16840.896383889358j), (-8.686466795335261e-07-1.9148922735557065e-07j))


## xlogy() function

In [8]:
func = special.xlogy(2,15)
print(func)

5.41610040220442


## exp10() function

It is revers of log function.
That means if log(10) = 1
then exp10(1) = 10

In [13]:

func= special.exp10(1)
print(func)
func = special.exp10(10)
print(func)

10.0
10000000000.0


## sindg() function
Here sindg means sine for angles in degree

In [17]:
func = special.sindg(60)
print(func)
print(special.sindg(30))
print(special.sindg(90))

0.8660254037844387
0.49999999999999994
1.0


## cosdg() function.
Here cosdg means cosine for angles in degree.

In [22]:
func = special.cosdg(60)
print(func)
print(special.cosdg(30))
print(special.cosdg(45))
print(special.cosdg(90))

0.49999999999999994
0.8660254037844387
0.7071067811865475
-0.0


## Calculating integration

In [24]:
from scipy import integrate
var = lambda x : x**3
func = integrate.quad(var,0,6)
print(func)

(323.99999999999994, 3.5971225997855064e-12)


## Calculating Double Integration

In [26]:
var = lambda y,x : x*y**4
func = integrate.dblquad(var,0,6,lambda x : 0, lambda x:1)
print(func)

(3.5999999999999996, 3.996802888650563e-14)


## Fourier Transforamtion.

In [28]:
import numpy as np
from scipy import fft

var = np.array([[2,2,3],[1,4,6]])
print(var)
# Fourier transform
print("\n",fft(var))

[[2 2 3]
 [1 4 6]]

 [[ 7. +0.j         -0.5+0.8660254j  -0.5-0.8660254j ]
 [11. +0.j         -4. +1.73205081j -4. -1.73205081j]]


## Solve the matrices

In [30]:
arr = np.array([[1,3],[4,5]])
arr1 = np.array([[4,7],[8,9]])

func = sp.linalg.solve(arr,arr1)
print(func)

[[ 0.57142857 -1.14285714]
 [ 1.14285714  2.71428571]]


## Calculate inverse of matrix

In [32]:
func = sp.linalg.inv(arr)
print(func)

[[-0.71428571  0.42857143]
 [ 0.57142857 -0.14285714]]
